var inited = false;
var inited_canvas = false;
var WALLH = document.body.offsetHeight;
var WALLW = document.body.offsetWidth;
var aspect;
var ingame = false;
var scene_main, scene, wall, renderer, camera, car, car_obj, ground, light_1, light_2, light_spot_right, light_spot_left, light_right_target, light_left_target;
var tire_left_1, tire_left_2, tire_left_3;
var tire_right_1, tire_right_2, tire_right_3;
var texture_loader = new THREE.TextureLoader();
var is_set_events = false;
var speed = 0;
var speed_wheel = 0.6;
var speed_max = 1;
var speed_min = 0;
var speed_min_score = 0.3;
var a = 0.004;
var is_accelerating = false, is_braking = false;
var keeping_left = false, keeping_right = false;
var obstacles = [];
var highscore = 0;
var highscore_player = "";
var playername = "";
var iv_score, iv_collision, iv_move;
var score = 0, stage = 1;
var obstacle_min = {x: -25, y: 0, z: -4.5};
var obstacle_max = {x: -290, y: 0, z: 4};
var distance = {x: 260, y: 0, z: 8};
var camera_to_car_diff = new THREE.Vector3(0, 0, 0);
var car_position_init = new THREE.Vector3(0, 0, 0);
var camera_position_init = new THREE.Vector3(7, 2, 0);
var end = {x: -315, y: 0, z: 0};
var tween;
var paused = false;